# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Dockerfile for Weather MCP Server
# Stage 1: Build
FROM node:lts-alpine AS builder
WORKDIR /app

# Copy source and manifests
COPY package.json tsconfig.json ./
COPY src ./src

# Install dependencies and build
RUN npm install
RUN npm run build

# Stage 2: Production image
FROM node:lts-alpine
WORKDIR /app

# Copy built artifacts
COPY --from=builder /app/build ./build
COPY package.json ./

# Install production dependencies only
RUN npm install --omit=dev

# Default command to run the MCP server
CMD ["node", "build/index.js"]
